
export default {
  en: {
    board_0_title: 'Welcome!',
    board_0_desc: 'My name is Ymp3 and I\'m here to help you convert YouTube videos into audio files. Awesome, right?',
    board_1_title:'EasyPeasy',
    board_1_desc: 'You like a song? Type its name in my search bar and you will get it, all of this without any ad.<br>And there is even more!',
    board_2_title: 'Multi-support',
    board_2_desc: 'You can use my services on any device, either on your computer or your smartphone by adding me to your Homescreen!',
    board_3_title: '',
    board_3_desc: 'Like any app, I need some support to keep working hard for you. Some apps use ads. I don\'t.<br>',
    board_4_title: 'It\'s a Win/Win',
    board_4_desc: 'When you use me, you enable a service that will allow me to transform time into cryptocurrency. Thanks to this amount of money, I can cover the costs of the servers that I use to work!<br><br>You can safely disable AdBlock :<b>there is no ad nor suspicious links!</b><br><br><span style="font-size: 10px;"><b style="color: red;">Important</b>: I <b>don\'t</b> get any personal information and my service is <b>free</b>.</span>',
    board_5_title: 'And easy!',
    board_5_desc: 'So, if you like my services, don\'t hesitate to support me by activating this feature sometimes. It\'s free and you can disable it anytime!',
    board_6_title: '<span style="font-size: 55px;margin-bottom: 5rem;display: block;">（＾人＾）</span><br>One last thing...',
    board_6_desc: 'All of those songs are created by great artists. That demands a lot of time and effort for them to keep us dreaming with their art. So please. Do not hesitate to like, share, comment, or buy their creations.<br><br><br><br><span style="font-size: 10px">If, as an artist, you don\'t want to see your music here, please send me an email (ayho.nine@gmail.com) with the name and the YouTube link - I will remove it.</span>',
    intro: 'What can I convert<br>for you?',
    placeholder: 'Youtube link, group or music name...',
    converted: 'Converted!',
    like: 'If you like it, buy it!',
    failed: 'Failed. Too long video (ಥ﹏ಥ)',
    typeother: 'Type another title <img style="width: 60px;vertical-align: text-bottom;" src="/static/easy.svg"/>',
    retry: 'That sucks but don\'t worry. You can type another title <img style="width: 60px;vertical-align: text-bottom;" src="/static/easy.svg"/>',
    pending: 'One moment please <img style="width: 60px;vertical-align: text-bottom;" src="/static/welcome.svg"/>',
    made: 'Created by',
    help: 'Made with',
    moreInfo: 'Your song is located in your Downloads/ folder :)',
    status_0: 'Converting...彡ﾟ◉ω◉ )つー☆*',
    status_25: 'Too damn long I know. (¬､¬)',
    status_50: 'Wait for it...ಠ_ಠ',
    status_75: 'Magic happening here! <br> (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧',
    understood: 'Let\'s go!',
    checkingCrypto: 'Please wait a minute...',
    checkingCryptoFailed: 'If you change your mind you can still support me by activating the service on the homepage',
    goAnyway: 'Let\'s go.. :(',
    next: 'Next',
    prev: 'Previous',
    adBlockRequest: 'Support me!<br>please disable adBlock<br>and Click ->',
    disableMining: 'To Disable<br>the service<br>Click ->',
    notDownload: 'Download didn\'t launch ?',
    retry: 'Retry'
  },
  fr: {
    board_0_title: 'Bienvenue !',
    board_0_desc: 'Je suis Ymp3 et je vais te permettre de convertir tes vidéos YouTube en fichier audio. Génial, non ?',
    board_1_title:'EasyPeasy!',
    board_1_desc: 'Tu aimes une musique ? Trouve-la grâce à ma barre de recherche, le tout sans pub !<br>Mais ce n\'est pas tout.',
    board_2_title: 'Multi-support',
    board_2_desc: 'Utilise mes services sur ton ordinateur ou sur ton smartphone en m\'ajoutant à ton écran d\'accueil !',
    board_3_title: '',
    board_3_desc: 'Comme toute application, j\'ai besoin d\'aide pour vivre. Certaines appli se servent des publicités. Moi pas.<br>',
    board_4_title: 'Gagnant - gagnant',
    board_4_desc: 'Un service s\'active lorsque tu m\'utilises. Il me permet de transformer le temps que tu passes ici en monnaie virtuelle qui me permettra de financer les serveurs nécessaires à mon bon fonctionnement !<br><br>Désactive Adblock en toute confiance : <b>tu ne verras ni pub, ni lien suspicieux</b>.<br><br><span style="font-size: 10px;"><b style="color: red;">Important</b>: Je ne récolte <b>aucune donnée personnelle</b>, et tout est <b>gratuit</b>.</span>',
    board_5_title: 'Et facile !',
    board_5_desc: 'Si tu aimes mes services, active cette fonctionnalité <b>gratuite</b> et  <b>désactivable</b> à tout moment !',
    board_6_title: '<span style="font-size: 55px;margin-bottom: 5rem;display: block;">（＾人＾）</span><br>Une dernière petite chose...',
    board_6_desc: 'N\'hésite pas à soutenir les artistes en achetant leurs albums, Ou en les faisant connaître !<br><br><br><br><span style="font-size: 10px">Si un artiste passe par là et ne veut pas voir ses musiques dans la liste de résultats, merci de m\'envoyer un email (ayho.nine@gmail.com) avec le nom et le lien YouTube de la musique.</span>',
    intro: 'Que souhaites-tu<br>convertir ?',
    placeholder: 'Lien Youtube, artiste, titre... ',
    converted: 'Conversion terminée !',
    like: 'Si tu aimes ce son, achète-le !',
    failed: 'Echec. Vidéo trop longue (ಥ﹏ಥ)',
    typeother: 'Tape un autre titre <img style="width: 60px;vertical-align: text-bottom;" src="/static/easy.svg"/>',
    retry: 'C\'est nul ! Mais t\'inquiète pas. Tu peux taper un autre titre <img style="width: 60px;vertical-align: text-bottom;" src="/static/easy.svg"/>',
    pending: 'Un moment s\'il te plaît <img style="width: 60px;vertical-align: text-bottom;" src="/static/welcome.svg"/>',
    made: 'Créé par',
    help: 'Fait avec',
    moreInfo: 'Ta musique se trouve dans ton dossier de téléchargement :)',
    status_0: 'Conversion en cours...<br>彡ﾟ◉ω◉ )つー☆*',
    status_25: 'Trop long je sais. (¬､¬)',
    status_50: 'Preeeesque fini ! ಠ_ಠ',
    status_75: 'Abracadabra... Magie ! <br> (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧',
    understood: 'C\'est parti !',
    checkingCrypto: 'Un instant...',
    checkingCryptoGranted: 'Un instant...',
    checkingCryptoFailed: 'Dommage :(. Si tu changes d\'avis tu peux activer le service sur l\'écran d\'accueil.',
    goAnyway: 'C\'est parti.. :(',
    next: 'Suivant',
    prev: 'Précédent',
    adBlockRequest: 'Pour me soutenir<br>désactive adBlock<br> et Click ->',
    disableMining: 'Pour me désactiver<br> le service<br>Click ->',
    notDownload: 'Le téléchargement ne s\'ests pas lancé ?',
    retry: 'Réessaie'
  }
}

